### ISSUE TITLE
OAI feed: Add unique id in feed -- use existing system field, not the identifier metadata

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#736] opened 2023-08-22 20:40 UTC
## Summary
Pals would like a unique id to display in the OAI feed only in oai_hyku. This will be different from the OAI identifier already in use. They want this mapped to a new field called `oai_id`.

## Testing Instructions
To see the going OAI Feed, visit ...

## Acceptance Criteria

- [ ] the unique id displays in the OAI feed under the `oai_id` element
- [ ] the unique id only displays in oai_hyku

**Comment by laritakr** [comment] 2023-08-25 15:55
Isn't this a duplicate of https://github.com/scientist-softserv/palni-palci/issues/733? Or if not, isn't it conflicting by using the same term for two purposes?

**Comment by ShanaLMoore** [comment] 2023-09-19 21:40
I'm not familiar enough with outgoing OAI but maybe this endpoint will suffice for testing? 

https://demo.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku

**Comment by ShanaLMoore** [comment] 2023-09-19 21:51
QA Results: Pass ✅ 

## Acceptance Criteria

- [ ] the unique id displays in the OAI feed under the `oai_id` element
- [ ] the unique id only displays in oai_hyku

Tested with: https://demo.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku

<img width="1341" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/abfaddac-454e-4c93-b3e7-87cb9bf5e556">

**Closed** 2023-10-03 19:05 UTC
Labels: Sprint: Odds and Ends
