### ISSUE TITLE
Contact Form not sending when email is updated

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#778] opened 2023-09-11 16:31 UTC
## Summary
In multiple production tenants on hykucommons.org, contact emails will not send once the email address is changed from the default to anything else. This occurs with both the "Contact email" and "Contact to email," regardless of whether they're set to the same or different addresses. 

## Accepted Criteria
- [ ] Contact emails will send to the email address specified, regardless of if it has been changed from the default

**Comment by ShanaLMoore** [comment] 2023-10-09 19:24
@ndroark Could you confirm where you are setting these contact emails?

**Comment by ndroark** [comment] 2023-10-09 19:33
Under Settings -> Account -> Contact email and Contact email to. We've used
both because we're not sure what the difference is between them.

**Comment by ShanaLMoore** [comment] 2023-10-09 20:24
Hi @ndroark We've since discovered that there is an allow list in aws's SES. This is the list of approved emails/domains. If a tenant wants to send an email beyond any of these domains, we'd have to set it up in their console and would need the SMTP configuration options. 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/8040960a-f03e-4da7-8357-8cb2b717c403)

**Comment by ndroark** [comment] 2023-10-09 20:30
So would the workflow simply be that when a user from a new domain (such as
anderson.edu) changes the contact email to their address, they contact us
(PALs) and we contact you (SoftServ) to make that change? Is any additional
information required beyond the domain of their email address?

<https://anderson.edu/>

NIC DON STANTON-ROARK

Archivist

Nicholson Library

o: 765.641.4285

He/Him

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by email if you have received this email by mistake and delete
this email from your system.

**Comment by ndroark** [comment] 2023-10-09 20:31
Or as a maintenance item, could we simply add all our current institutional
domains in one ticket, and then add new institutions as soon as they come
on board? Is there a possibility in the future that we could make this
configurable from the superadmin side so it doesn't require dev
intervention?

<https://anderson.edu/>

NIC DON STANTON-ROARK

Archivist

Nicholson Library

o: 765.641.4285

He/Him

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by email if you have received this email by mistake and delete
this email from your system.

**Comment by ShanaLMoore** [comment] 2023-10-09 20:54
**So would the workflow simply be that when a user from a new domain (such as anderson.edu) changes the contact email to their address, they contact us (PALs) and we contact you (SoftServ) to make that change?**

- yes

**Is any additional information required beyond the domain of their email address?**

- yes, more would required. Take a look at [these configurations](https://github.com/scientist-softserv/palni-palci/blob/main/ops/production-deploy.tmpl.yaml#L157-L170) to get an idea of what would be needed. 

**Or as a maintenance item, could we simply add all our current institutional domains in one ticket, and then add new institutions as soon as they come on board?** 

- Yes, that could be possible. Then any email from those domains would be approved. ie: shana@anderson.edu

**Is there a possibility in the future that we could make this configurable from the super admin side so it doesn't require dev intervention?**

- maybe! Speak to @jillpe about getting an estimate of work for it. This would be something that only super admins (like yourself) should be able to configure.

**Comment by ndroark** [comment] 2023-10-09 20:59
On the SMTP configurations, how would a user at an institution get any of
that information? Does that seem like something a university IT department
would have access to?


<https://anderson.edu/>

NIC DON STANTON-ROARK

Archivist

Nicholson Library

o: 765.641.4285

He/Him

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by email if you have received this email by mistake and delete
this email from your system.

**Comment by ShanaLMoore** [comment] 2023-10-09 21:45
> On the SMTP configurations, how would a user at an institution get any of that information? Does that seem like something a university IT department would have access to? 

That'd probably be the place to start.

**Comment by ShanaLMoore** [comment] 2023-10-11 02:28
@ndroark thinking more about it, I think your suggestion of setting up domains for the universities sounds like a more straightforward plan. That way anyone with that domain can have a valid contact email set and there would be less back and forth types of communications/wait time.

**Comment by ShanaLMoore** [comment] 2023-10-11 02:30
@ndroark thinking more about it, I think your suggestion of setting up domains for the various universities (+ adding new ones as they onboard) sounds like a more straightforward plan. That way anyone with that domain can have a valid contact email set and there would be less back and forth types of communications/wait time. We'd prob still need info from their IT but still, it'd be a one time thing vs however many would be required if we did so individually.

**Comment by ShanaLMoore** [comment] 2023-10-11 02:30
@ndroark thinking more about it, I think your suggestion of setting up domains for the various universities (+ adding new ones as they onboard) sounds like a more straightforward plan. That way anyone with that domain can have a valid contact email set and there would be less back and forth types of communications/wait time. We'd prob still need info from their IT but still, it'd be a one time thing vs however many would be required if we did so individually.

Let us know how you'd like to proceed. 

Is it ok to close this ticket?

**Comment by ShanaLMoore** [comment] 2023-10-16 22:58
Re work - user can't save changes to contact_email on account settings form.

**Comment by ShanaLMoore** [comment] 2023-10-16 23:27
![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/c309288d-8f56-49f3-89bf-28b736668ff0)

**Comment by ShanaLMoore** [comment] 2023-10-16 23:34
make it generic and contribute back to hyku: the sites' domain

**Comment by ndroark** [comment] 2023-10-16 23:47
Modify that to "the site's domain" though

**Comment by ShanaLMoore** [comment] 2023-10-17 17:19
@ndroark we confirmed that when we updated the contact_email_to to kirk's email, he was able to receive the email that was submitted via the contact form. 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/32ad01ae-a3d8-4c0f-ba61-532b464307a9)

**Closed** 2023-10-27 15:23 UTC
Labels: October Sprint
